name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: NPM_TOKEN
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - run: npm install -g npm@latest
      - run: node --version && npm --version
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm publish --access public
